#!/usr/bin/env python3

import struct
import sys
from socket import *

import struct

import struct

def create_dns_response(data, ip_address):
    domain_name = parse_dns_query(data)
    id = data[:2]
    flags = b'\x81\x80'  
    questions = b'\x00\x01'  
    answers = b'\x00\x01'  
    authority = b'\x00\x00' 
    additional = b'\x00\x00' 
    header = id + flags + questions + answers + authority + additional
    
    domain = domain_name.encode('utf-8') + b'\x00'
    
    q_type = b'\x00\x01'  
    q_class = b'\x00\x01'  
    ttl = b'\x00\x00\x00\x00'  # no caching
    length = b'\x00\x04'  
    addr = inet_aton(ip_address)
    resource_section = q_type + q_class + ttl + length + addr
    

    response = header + domain + resource_section
    
    return response
    

def parse_dns_query(data):
    domain_start = 12
    domain_end = data.find(b'\x00', domain_start)
    domain_name = data[domain_start:domain_end].decode('utf-8')
    
    return domain_name




if __name__ == "__main__":
    if len(sys.argv) != 5:
        print("Usage: python3", sys.argv[0], "<topo-dir>", "log", "<listen-port>", "decision-method>")
        sys.exit()
        
    topo_dir = str(sys.argv[1])
    log_file = str(sys.argv[2])
    listen_port = int(sys.argv[3])
    decision_method = str(sys.argv[4])
    ip_addr = "5.0.0.1"
    topo_dns_file = topo_dir + '/topo' + topo_dir[-1] + ".dns"
    topo_servers = topo_dir + '/topo' + topo_dir[-1] + ".servers"
    
    with open(topo_dns_file, "r") as file:
        ip_addr = file.read().strip()
        
    server_ip_responses = []
    with open(topo_servers, "r") as file:
        server_ip_responses = [x for x in file.read().split("\n") if x]
    
    print("topo_dir:", topo_dir, "log_file:", log_file, "listen_port:", listen_port, "decision_method:", decision_method, "ip-addr:", ip_addr)
    
    server_socket = socket(AF_INET, SOCK_DGRAM)
    server_socket.bind((ip_addr, listen_port))
    
    try:
        while True:
            data, client_address = server_socket.recvfrom(512)
            print(f"Received message from {client_address}: {data}")
            response = create_dns_response(data, ip_addr)
            server_socket.sendto(response, client_address)
            
    except KeyboardInterrupt:
        print("\nServer is shutting down.")
    finally:
        server_socket.close()

    
      
